### ISSUE TITLE
Proxy leaks socket connections

### ISSUE THREAD

**Issue by devimc** [kata-containers/proxy#77]
# Description of problem

proxy leaks socket connections each time a new command is executed into the container

```
$ docker run -dti --name foo debian bash
14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e
$ sudo netstat -pdaC | grep "/proxy"
unix  2      [ ACC ]     STREAM     LISTENING     1101409  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1101999  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1095675  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
```

```
$ for i in $(seq 1 500); do (docker exec foo sleep 5 &); done
$ sudo netstat -pdaC | grep "/proxy"
unix  2      [ ACC ]     STREAM     LISTENING     1101409  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1106216  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1101999  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1102018  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1106145  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1106078  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1106240  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1106244  -                    /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1105054  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1095675  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1107077  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1099697  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1107115  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
unix  2      [ ]         STREAM     CONNECTED     1102161  2852/kata-proxy      /run/vc/sbs/14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e/proxy.sock
```

**each time `for i in $(seq 1 500); do (docker exec foo sleep 5 &); done` is executed the number of connections increase**

```
$ for i in $(seq 1 500); do (docker exec foo sleep 5 &); done
$ sudo netstat -pdaC | grep "/proxy" | wc -l
65
$ sleep 5
$ for i in $(seq 1 500); do (docker exec foo sleep 5 &); done
$ sudo netstat -pdaC | grep "/proxy" | wc -l
85
$ sleep 5
$ for i in $(seq 1 500); do (docker exec foo sleep 5 &); done
$ sudo netstat -pdaC | grep "/proxy" | wc -l
112
```

seems like proxy leaks socket connections

**[Update]**

agent is no more able to `exec` processes inside `foo` container, might be a problem with the subreaper?

```
goroutine 5 [syscall]:
runtime.notetsleepg(0x1113960, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:227 +0x42 fp=0xc420047f80 sp=0xc420047f50 pc=0x4122b2
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6 fp=0xc420047fa8 sp=0xc420047f80 pc=0x443b06
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22 fp=0xc420047fe0 sp=0xc420047fa8 pc=0x543dc2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420047fe8 sp=0xc420047fe0 pc=0x45aaa1
created by os/signal.init.0x
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 1 [runnable, locked to thread]:
syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc4201b8ba0, 0x80000, 0x0, 0x0, 0x0, 0x4, 0x80000, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.openat(0xffffffffffffff9c, 0xb14ac3, 0xb, 0x80000, 0xc400000000, 0xc420032000, 0xc4201b5460, 0x4902b0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:38 +0xae
syscall.Open(0xb14ac3, 0xb, 0x80000, 0xc400000000, 0xc42006e7a0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:51 +0x50
os.openFileNolog(0xb14ac3, 0xb, 0x0, 0x0, 0xc420095810, 0x1, 0xc4201b5400)
	/usr/local/go/src/os/file_unix.go:168 +0x7a
os.OpenFile(0xb14ac3, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:269 +0x5f
os.Open(0xb14ac3, 0xb, 0xc4201c0000, 0x1000, 0x1000)
	/usr/local/go/src/os/file.go:250 +0x46
github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer/user.GetExecUserPath(0xc4200414d0, 0x3, 0xc4201b57a8, 0xb14ac3, 0xb, 0xb13fb2, 0xa, 0x0, 0x0, 0x0)
	/home/x/go/src/github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer/user/user.go:244 +0x56
github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer.setupUser(0xc4201a4000, 0x0, 0x0)
	/home/x/go/src/github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer/init_linux.go:263 +0xd1
github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer.finalizeNamespace(0xc4201a4000, 0xc42016ba60, 0xd)
	/home/x/go/src/github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer/init_linux.go:145 +0x108
github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer.(*linuxSetnsInit).Init(0xc42016ba60, 0x5, 0xc42000e0f0)
	/home/x/go/src/github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer/setns_init_linux.go:58 +0x8f
github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc420190090, 0x0, 0x0)
	/home/x/go/src/github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go:321 +0x3e0
main.init.0()
	/home/x/go/src/github.com/kata-containers/agent/agent.go:776 +0x96

rax    0x0
rbx    0x7fc628bd2840
rcx    0x7fc628a27247
rdx    0x0
rdi    0x2
rsi    0x7fc628181890
rbp    0xbb25ae
rsp    0x7fc628181890
r8     0x0
r9     0x7fc628181890
r10    0x8
r11    0x246
r12    0x19c0470
r13    0xf1
r14    0x11
r15    0x0
rip    0x7fc628a27247
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f28d7252247 m=3 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f28d7252247
stack: frame={sp:0x7f28d69ac890, fp:0x0} stack=[0x7f28d61ad290,0x7f28d69ace90)
00007f28d69ac790:  0000000000000005  0000ffff00001fa0 
00007f28d69ac7a0:  00007f28d69acca0  00000000020f1470 
00007f28d69ac7b0:  00000000000000f1  0000000000000011 
00007f28d69ac7c0:  0000000000000000  00007f28d74389d3 
00007f28d69ac7d0:  0000000000000005  0000000000000000 
00007f28d69ac7e0:  00007f28d69acb80  00007f28d7222ce0 
00007f28d69ac7f0:  00007f28d69acbb0  00007f28d744026a 
00007f28d69ac800:  0000000000000000  0000000000000000 
00007f28d69ac810:  0000000000000000  00007f28d69acca0 
00007f28d69ac820:  2525252525252525  2525252525252525 
00007f28d69ac830:  00000000000000ff  0000000000000000 
00007f28d69ac840:  00000000000000ff  0000000000000000 
00007f28d69ac850:  0000000000000001  000000000000000a 
00007f28d69ac860:  000000000000000e  000000000000000e 
00007f28d69ac870:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac880:  0000000400000004  0000000400000004 
00007f28d69ac890: <0000000000000000  00007f28d0000800 
00007f28d69ac8a0:  20636f6c6c616d00  203a64656c696166 
00007f28d69ac8b0:  0000000000000000  0000000000000000 
00007f28d69ac8c0:  0000000000000000  0000000000000000 
00007f28d69ac8d0:  0000000000000000  0000000000000000 
00007f28d69ac8e0:  0000000000000000  000000c420000180 
00007f28d69ac8f0:  0000000000000000  000000000045aaa1 <runtime.goexit+1> 
00007f28d69ac900:  0000000000000000  0000000000000000 
00007f28d69ac910:  fffffffe7fffffff  ffffffffffffffff 
00007f28d69ac920:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac930:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac940:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac950:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac960:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac970:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac980:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f28d7252247
stack: frame={sp:0x7f28d69ac890, fp:0x0} stack=[0x7f28d61ad290,0x7f28d69ace90)
00007f28d69ac790:  0000000000000005  0000ffff00001fa0 
00007f28d69ac7a0:  00007f28d69acca0  00000000020f1470 
00007f28d69ac7b0:  00000000000000f1  0000000000000011 
00007f28d69ac7c0:  0000000000000000  00007f28d74389d3 
00007f28d69ac7d0:  0000000000000005  0000000000000000 
00007f28d69ac7e0:  00007f28d69acb80  00007f28d7222ce0 
00007f28d69ac7f0:  00007f28d69acbb0  00007f28d744026a 
00007f28d69ac800:  0000000000000000  0000000000000000 
00007f28d69ac810:  0000000000000000  00007f28d69acca0 
00007f28d69ac820:  2525252525252525  2525252525252525 
00007f28d69ac830:  00000000000000ff  0000000000000000 
00007f28d69ac840:  00000000000000ff  0000000000000000 
00007f28d69ac850:  0000000000000001  000000000000000a 
00007f28d69ac860:  000000000000000e  000000000000000e 
00007f28d69ac870:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac880:  0000000400000004  0000000400000004 
00007f28d69ac890: <0000000000000000  00007f28d0000800 
00007f28d69ac8a0:  20636f6c6c616d00  203a64656c696166 
00007f28d69ac8b0:  0000000000000000  0000000000000000 
00007f28d69ac8c0:  0000000000000000  0000000000000000 
00007f28d69ac8d0:  0000000000000000  0000000000000000 
00007f28d69ac8e0:  0000000000000000  000000c420000180 
00007f28d69ac8f0:  0000000000000000  000000000045aaa1 <runtime.goexit+1> 
00007f28d69ac900:  0000000000000000  0000000000000000 
00007f28d69ac910:  fffffffe7fffffff  ffffffffffffffff 
00007f28d69ac920:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac930:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac940:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac950:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac960:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac970:  ffffffffffffffff  ffffffffffffffff 
00007f28d69ac980:  ffffffffffffffff  ffffffffffffffff
OCI runtime exec failed: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "read init-p: connection reset by peer": unknown
OCI runtime exec failed: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "read init-p: connection reset by peer": unknown
OCI runtime exec failed: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "read init-p: connection reset by peer": unknown
OCI runtime exec failed: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "read init-p: connection reset by peer": unknown
```

**Note:** Only bash is running inside the container

```
$ sudo kata-runtime ps 14058201a6116532ce6e7afd163576a6d9396380aa60633236c8c21e87a30b7e
UID        PID  PPID  C STIME TTY          TIME CMD
root       134   114  0 17:36 ?        00:00:00 bash
```

**Comment by devimc** [comment]
related to https://github.com/kata-containers/agent/pull/263

**Comment by sboeuf** [comment]
FYI, I have started to look into this and I can easily reproduce it. I think the problem is about the multiple go routines that handle each connection and supposed to close them properly at the end.
Maybe the connection handler gets reused and this actually causes some race conditions sometimes. Need more investigations but I agree we should solve this pretty quickly, and it should not be too hard.

**Comment by sboeuf** [comment]
@devimc 
More debug on my side: the problem comes from one of the two Copy() stream that is not closed, meaning the function `cleanup()` gets never called and does not close the expected channels. Specifically, the CopyStream() in proxy.go reading from the stream representing the connection between proxy and agent is never closed sometimes. Need to check the yamux handling of the connection inside the agent.
